/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sysadv.telas;

import br.com.sysadv.dal.Conexao;
import java.util.Calendar;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author brenno
 */
public class CadCompromisso extends javax.swing.JInternalFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form NewJInternalFrame
     */
    public CadCompromisso() {
        initComponents();
        con = Conexao.Conectar();
    }
    
    public void tbComp(){
        int setar = tbAdv.getSelectedRow();
        txtIdComp.setText(tbAdv.getModel().getValueAt(setar, 0).toString());
    }

    public void pesqAdv() {
        String sql = "select idadv as ID,nomeAdv as Nome,cpfAdv as CPF,sexoAdv as Sexo from tb_advogado where nomeAdv like ?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtPesqAdv.getText() + "%");
            rs = pst.executeQuery();
            tbAdv.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void cadastrarComp() {
        String sql = "insert into tb_agenda (idadv,nomeComp,dataComp,horaComp,descComp) values (?,?,?,?,?)";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtIdComp.getText());
            pst.setString(2, txtNomeComp.getText());
            int dia = dataComp.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mes = dataComp.getCalendar().get(Calendar.MONTH) + 1;
            int ano = dataComp.getCalendar().get(Calendar.YEAR);
            String dataParaMySQL = ano + "-" + mes + "-" + dia;
            pst.setString(3, dataParaMySQL);
            pst.setString(4, txtHoraComp.getText());
            pst.setString(5, txtDescComp.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Compromisso cadastrado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void alterarComp() {
        String sql = "update tb_agenda set nomeComp=?,dataComp=?,horaComp=?,descComp=? where idcomp=?";
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, txtNomeComp.getText());
            int dia = dataComp.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mes = dataComp.getCalendar().get(Calendar.MONTH) + 1;
            int ano = dataComp.getCalendar().get(Calendar.YEAR);
            String dataParaMySQL = ano + "-" + mes + "-" + dia;
            pst.setString(2, dataParaMySQL);
            pst.setString(3, txtHoraComp.getText());
            pst.setString(4, txtDescComp.getText());
            pst.setString(5, txtIdComp.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Compromisso alterado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeComp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoraComp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescComp = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAdv = new javax.swing.JTable();
        btnEditarComp = new javax.swing.JButton();
        btnExcluirComp = new javax.swing.JButton();
        btnCadComp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dataComp = new com.toedter.calendar.JDateChooser();
        txtIdComp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPesqAdv = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Novo Compromisso");

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setText("Nome do compromisso");

        jLabel3.setText("Descrição");

        jLabel4.setText("Horario do compromisso");

        txtDescComp.setColumns(20);
        txtDescComp.setRows(5);
        jScrollPane2.setViewportView(txtDescComp);

        tbAdv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAdvMouseClicked(evt);
            }
        });
        tbAdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbAdvKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbAdv);

        btnEditarComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Modify.png"))); // NOI18N
        btnEditarComp.setText("Alterar");
        btnEditarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnExcluirComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Delete.png"))); // NOI18N
        btnExcluirComp.setText("Excluir");
        btnExcluirComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCadComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Create.png"))); // NOI18N
        btnCadComp.setText("Cadastrar");
        btnCadComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCompActionPerformed(evt);
            }
        });

        jLabel6.setText("Data do compromisso");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/View.png"))); // NOI18N
        jLabel9.setText("Pesquisar advogado");

        txtPesqAdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqAdvKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesqAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHoraComp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(dataComp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnCadComp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(btnEditarComp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(btnExcluirComp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeComp, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPesqAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtHoraComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(dataComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluirComp)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCompActionPerformed
        cadastrarComp();
    }//GEN-LAST:event_btnCadCompActionPerformed

    private void txtPesqAdvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqAdvKeyReleased
        pesqAdv();
    }//GEN-LAST:event_txtPesqAdvKeyReleased

    private void tbAdvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbAdvKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAdvKeyReleased

    private void tbAdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAdvMouseClicked
        tbComp();
    }//GEN-LAST:event_tbAdvMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadComp;
    private javax.swing.JButton btnEditarComp;
    private javax.swing.JButton btnExcluirComp;
    private com.toedter.calendar.JDateChooser dataComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAdv;
    private javax.swing.JTextArea txtDescComp;
    private javax.swing.JTextField txtHoraComp;
    private javax.swing.JTextField txtIdComp;
    private javax.swing.JTextField txtNomeComp;
    private javax.swing.JTextField txtPesqAdv;
    // End of variables declaration//GEN-END:variables
}
