/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sysadv.telas;

import br.com.sysadv.classes.BackgroundedDesktopPane;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author brenno
 */
public class Inicial extends javax.swing.JFrame {

    Connection conexao;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Inicial
     */

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    public Inicial() {
        initComponents();
        Desktop.setBorder(new BackgroundedDesktopPane());
        this.setExtendedState(Inicial.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        mItemCliente = new javax.swing.JMenuItem();
        mItemAdv = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemVerPro = new javax.swing.JMenuItem();
        mItemNovoPro = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        mItemAgenda = new javax.swing.JMenuItem();
        mItemCom = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysADV");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(294, 30));

        menuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/User_group.png"))); // NOI18N
        menuCadastrar.setText("Cadastrar");

        mItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Male.png"))); // NOI18N
        mItemCliente.setText("Cliente");
        mItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemClienteActionPerformed(evt);
            }
        });
        mItemCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mItemClienteKeyPressed(evt);
            }
        });
        menuCadastrar.add(mItemCliente);

        mItemAdv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mItemAdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Boss.png"))); // NOI18N
        mItemAdv.setText("Advogado");
        mItemAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAdvActionPerformed(evt);
            }
        });
        menuCadastrar.add(mItemAdv);

        jMenuBar1.add(menuCadastrar);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Text.png"))); // NOI18N
        jMenu2.setText("Processos");

        mItemVerPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemVerPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Text.png"))); // NOI18N
        mItemVerPro.setText("Ver Processos");
        mItemVerPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVerProActionPerformed(evt);
            }
        });
        jMenu2.add(mItemVerPro);

        mItemNovoPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mItemNovoPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Notes.png"))); // NOI18N
        mItemNovoPro.setText("Novo Processo");
        mItemNovoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNovoProActionPerformed(evt);
            }
        });
        jMenu2.add(mItemNovoPro);

        jMenuBar1.add(jMenu2);

        menuAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Calendar.png"))); // NOI18N
        menuAgenda.setText("Agenda");
        menuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaActionPerformed(evt);
            }
        });

        mItemAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Notes.png"))); // NOI18N
        mItemAgenda.setText("Ver agenda");
        mItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAgendaActionPerformed(evt);
            }
        });
        menuAgenda.add(mItemAgenda);

        mItemCom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mItemCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Calendar.png"))); // NOI18N
        mItemCom.setText("Novo Compromisso");
        mItemCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemComActionPerformed(evt);
            }
        });
        menuAgenda.add(mItemCom);

        jMenuBar1.add(menuAgenda);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Info.png"))); // NOI18N
        menuAjuda.setText("Ajuda");

        menuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Help_book_3d.png"))); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Exit.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem1);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1031, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mItemClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemClienteKeyPressed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
        Desktop.add(sobre);
        centralizaForm(sobre);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void mItemAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAdvActionPerformed
        CadAdvogado adv = new CadAdvogado();
        adv.setVisible(true);
        Desktop.add(adv);
        centralizaForm(adv);
    }//GEN-LAST:event_mItemAdvActionPerformed

    private void mItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemClienteActionPerformed
        CadCliente cli = new CadCliente();
        cli.setVisible(true);
        Desktop.add(cli);
        centralizaForm(cli);
    }//GEN-LAST:event_mItemClienteActionPerformed

    private void menuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaActionPerformed

    }//GEN-LAST:event_menuAgendaActionPerformed

    private void mItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAgendaActionPerformed
        Agenda agenda = new Agenda();
        agenda.setVisible(true);
        Desktop.add(agenda);
        centralizaForm(agenda);
    }//GEN-LAST:event_mItemAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mItemVerProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVerProActionPerformed
        Processos processos = new Processos();
        processos.setVisible(true);
        Desktop.add(processos);
        centralizaForm(processos);
    }//GEN-LAST:event_mItemVerProActionPerformed

    private void mItemNovoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNovoProActionPerformed
        CadProcessos cadPro = new CadProcessos();
        cadPro.setVisible(true);
        Desktop.add(cadPro);
        centralizaForm(cadPro);
    }//GEN-LAST:event_mItemNovoProActionPerformed

    private void mItemComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemComActionPerformed
        CadCompromisso agenda = new CadCompromisso();
        agenda.setVisible(true);
        Desktop.add(agenda);
        centralizaForm(agenda);
    }//GEN-LAST:event_mItemComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mItemAdv;
    private javax.swing.JMenuItem mItemAgenda;
    private javax.swing.JMenuItem mItemCliente;
    private javax.swing.JMenuItem mItemCom;
    private javax.swing.JMenuItem mItemNovoPro;
    private javax.swing.JMenuItem mItemVerPro;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
