/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sysadv.telas;

import br.com.sysadv.classes.BackgroundedDesktopPane;

/**
 *
 * @author brenno
 */
public class Processos extends javax.swing.JFrame {

    /**
     * Creates new form Processos
     */
    public Processos() {
        initComponents();
        desktopPro.setBorder(new BackgroundedDesktopPane());
        this.setExtendedState(Inicial.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPro = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemSobrePro = new javax.swing.JMenuItem();
        mItemSairPro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(52, 30));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Text.png"))); // NOI18N
        jMenu1.setText("Processos");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Text_preview.png"))); // NOI18N
        jMenuItem2.setText("Visualizar Processos");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Info.png"))); // NOI18N
        jMenu2.setText("Ajuda");

        mItemSobrePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Help_book_3d.png"))); // NOI18N
        mItemSobrePro.setText("Sobre");
        mItemSobrePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSobreProActionPerformed(evt);
            }
        });
        jMenu2.add(mItemSobrePro);

        mItemSairPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sysadv/icones/Exit.png"))); // NOI18N
        mItemSairPro.setText("Sair");
        mItemSairPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairProActionPerformed(evt);
            }
        });
        jMenu2.add(mItemSairPro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPro, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPro, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1034, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemSairProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairProActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mItemSairProActionPerformed

    private void mItemSobreProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSobreProActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
        desktopPro.add(sobre);
    }//GEN-LAST:event_mItemSobreProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mItemSairPro;
    private javax.swing.JMenuItem mItemSobrePro;
    // End of variables declaration//GEN-END:variables
}
